// altshift.v

// Generated using ACDS version 20.1 711

`timescale 1 ps / 1 ps
module altshift (
		input  wire        aclr,     //  altshift_taps_input.aclr
		input  wire        clken,    //                     .clken
		input  wire        clock,    //                     .clock
		input  wire [7:0]  shiftin,  //                     .shiftin
		output wire [7:0]  shiftout, // altshift_taps_output.shiftout
		output wire [15:0] taps      //                     .taps
	);

	altshift_altshift_taps_201_as43lbi altshift_taps_0 (
		.aclr     (aclr),     //  altshift_taps_input.aclr
		.clken    (clken),    //                     .clken
		.clock    (clock),    //                     .clock
		.shiftin  (shiftin),  //                     .shiftin
		.shiftout (shiftout), // altshift_taps_output.shiftout
		.taps     (taps)      //                     .taps
	);

endmodule
